name: OpenTofu TDA

on:
  workflow_dispatch:
#  push:
#    branches:
#      - main
#    paths:
#      - 'TDA/**'
#      - 'modules/namespace/**'
#      - '.github/workflows/opentofu-tda.yml'

jobs:
  plan-apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: TDA

    env:
      TF_VAR_vault_token: ${{ secrets.TDA_VAULT_TOKEN }}
      TF_VAR_ldap_bindpass: ${{ secrets.TDA_LDAP_BINDPASS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.8.8

      - name: Tofu init
        run: tofu init

      - name: Tofu fmt check
        run: tofu fmt -check -recursive

      - name: Tofu validate
        run: tofu validate

      - name: Tofu plan
        run: tofu plan -input=false -out=tfplan

      - name: Tofu apply
        if: github.ref == 'refs/heads/main'
        run: tofu apply -auto-approve -input=false tfplan
